sudo: required
services:
  - docker

before_intsall:
 - docker build -t aryan9600/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true aryan9600/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-112467108895"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
